/**
 * Extracts glyph outlines from the bundled Noto fonts into src/fonts/glyphs.data.ts.
 *
 * Runtime code never parses a font: frame text is drawn from these pre-extracted
 * outlines, so the browser and Node emit the same path string (QD-D8). Arabic is
 * shaped in-house to Unicode presentation forms (opentype.js cannot apply Noto
 * Sans Arabic's GSUB), so the Arabic subset is the presentation-form blocks.
 *
 * Run: npm run build:glyphs (needs the devDependencies installed).
 */
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
import opentype from 'opentype.js';

const require = createRequire(import.meta.url);
const fontFile = (pkg, file) => path.join(path.dirname(require.resolve(`${pkg}/package.json`)), 'files', file);

const ranges = (...pairs) => pairs.flatMap(([a, b]) => Array.from({ length: b - a + 1 }, (_, i) => a + i));

const SOURCES = [
    {
        key: 'latin',
        file: fontFile('@fontsource/noto-sans', 'noto-sans-latin-700-normal.woff'),
        codepoints: ranges([0x20, 0x7e], [0xa0, 0xff], [0x2013, 0x2014], [0x2018, 0x201d], [0x2026, 0x2026]),
    },
    {
        key: 'arabic',
        file: fontFile('@fontsource/noto-sans-arabic', 'noto-sans-arabic-arabic-700-normal.woff'),
        codepoints: ranges([0x060c, 0x060c], [0x061b, 0x061f], [0x0621, 0x064a], [0x0660, 0x066c], [0xfe70, 0xfefc]),
    },
];

/** Font units are integers; keep them so the data stays small and exact. */
const n = (v) => String(Math.round(v));

const toCompactPath = (glyph) =>
    glyph.path.commands
        .map((c) => {
            switch (c.type) {
                case 'M':
                case 'L':
                    return `${c.type}${n(c.x)} ${n(-c.y)}`;
                case 'Q':
                    return `Q${n(c.x1)} ${n(-c.y1)} ${n(c.x)} ${n(-c.y)}`;
                case 'C':
                    return `C${n(c.x1)} ${n(-c.y1)} ${n(c.x2)} ${n(-c.y2)} ${n(c.x)} ${n(-c.y)}`;
                default:
                    return 'Z';
            }
        })
        .join('');

const fonts = {};
const glyphs = {};
for (const source of SOURCES) {
    const font = opentype.parse(fs.readFileSync(source.file).buffer);
    fonts[source.key] = { unitsPerEm: font.unitsPerEm, ascender: font.ascender, descender: font.descender };
    for (const cp of source.codepoints) {
        if (glyphs[cp]) continue;
        const index = font.charToGlyphIndex(String.fromCodePoint(cp));
        if (!index) continue;
        const glyph = font.glyphs.get(index);
        glyphs[cp] = [source.key, Math.round(glyph.advanceWidth), toCompactPath(glyph)];
    }
}

const out = `/* eslint-disable */
// GENERATED by scripts/build-glyphs.mjs — do not edit by hand.
// Outlines from Noto Sans Bold and Noto Sans Arabic Bold (SIL Open Font License 1.1, see OFL.txt).
// Path data is in font units with the y axis pointing down (baseline at y = 0).
import type { IGlyphTable } from '../interface';

export const QR_GLYPH_TABLE: IGlyphTable = ${JSON.stringify({ fonts, glyphs })};
`;
fs.writeFileSync(path.join('src', 'fonts', 'glyphs.data.ts'), out);
console.log(`glyphs: ${Object.keys(glyphs).length}, bytes: ${out.length}`);
